-- COMPANY VIDEOS: one production pipeline, not two.
--
-- A reusable company video goes through exactly the workflow a site induction does -
-- script, review, approve, narrate, caption, render, review, publish - so it uses the
-- same tables. A second set would mean a second queue, a second audit trail, and two
-- places to fix everything from now on.
--
-- `jobSiteId` becomes NULLABLE because a company video belongs to no project. The
-- alternative was a synthetic "company" JobSite, which would appear in project lists
-- and compliance figures and need excluding by hand for ever.
--
-- ALL ADDITIVE OR WIDENING, so this is safe to apply before the build that uses it:
--   * the new columns are nullable or defaulted, and the live build selects columns
--     explicitly rather than SELECT *;
--   * DROP NOT NULL cannot fail and cannot lose anything;
--   * the unique index on (libraryAssetId, version) is satisfied trivially by every
--     existing row, because they all have libraryAssetId NULL and Postgres treats
--     NULLs as distinct. That distinctness is also why the existing
--     (jobSiteId, version) unique does NOT constrain company videos, and why this
--     second index has to exist at all.
--
-- Generated by `prisma migrate diff --from-migrations --to-schema-datamodel`.

-- CreateEnum
CREATE TYPE "InductionVideoScope" AS ENUM ('SITE', 'COMPANY');

-- AlterTable
ALTER TABLE "InductionVideo" ADD COLUMN     "libraryAssetId" TEXT,
ADD COLUMN     "scope" "InductionVideoScope" NOT NULL DEFAULT 'SITE',
ADD COLUMN     "sourceModuleRevisionId" TEXT,
ALTER COLUMN "jobSiteId" DROP NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "InductionVideo_libraryAssetId_version_key" ON "InductionVideo"("libraryAssetId", "version");

-- AddForeignKey
ALTER TABLE "InductionVideo" ADD CONSTRAINT "InductionVideo_libraryAssetId_fkey" FOREIGN KEY ("libraryAssetId") REFERENCES "LibraryAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

