/**
 * Minimal, dependency-free CSV serialisation shared by the platform export
 * routes. Quotes any cell containing a comma, quote or newline (RFC 4180),
 * neutralises spreadsheet formula injection, and joins rows with CRLF for
 * maximum spreadsheet compatibility.
 */

export type CsvValue = string | number | boolean | null | undefined;

/**
 * Serialise one CSV cell.
 *
 * CSV / formula injection: a field that begins with `=`, `+`, `-` or `@` (or a
 * tab / carriage return) can be executed as a formula or command by Excel or
 * Google Sheets when a user opens the exported file. We neutralise it by
 * prefixing a single quote, which forces the cell to be treated as text.
 * Spreadsheets strip that quote on display, so the exported value is preserved
 * for the reader. The guard is only applied to string values — numbers and
 * booleans are generated by the app, never attacker-controlled, so they keep
 * their native type (e.g. a real `-5` stays the number -5, not text).
 */
export function csvCell(value: CsvValue): string {
  let s = value === null || value === undefined ? '' : String(value);
  if (typeof value === 'string' && /^[=+\-@\t\r]/.test(s)) {
    s = `'${s}`;
  }
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Build a CSV document from a header row and data rows. */
export function toCsv(header: string[], rows: CsvValue[][]): string {
  return [header, ...rows]
    .map((row) => row.map(csvCell).join(','))
    .join('\r\n');
}
