import { notFound, redirect } from 'next/navigation';
import { PlatformShell } from '@/components/platform/PlatformShell';
import { Breadcrumbs } from '@/components/platform/Breadcrumbs';
import { requirePlatformViewer } from '@/services/platformUsers/platformAccess';
import { canManageInductionVideos } from '@/services/inductionVideo/inductionVideoPermissions';
import { getVideo } from '@/services/inductionVideo/inductionVideoService';
import { formatDateTimeUK } from '@/lib/datetime';
import { InductionVideoStatusBadge } from '@/components/platform/InductionVideoStatusBadge';
import { ScriptEditor } from '@/components/platform/ScriptEditor';

export const dynamic = 'force-dynamic';

/** One version: its scenes, its history, and the decision to approve it. */
export default async function InductionVideoPage({
  params,
}: {
  params: { videoId: string };
}) {
  const viewer = await requirePlatformViewer();
  if (!canManageInductionVideos(viewer.role)) redirect('/platform/dashboard');

  const detail = await getVideo(viewer, params.videoId);
  if (!detail) notFound();
  const { video, stale, warnings, canApprove } = detail;

  const blocking = Array.isArray(video.blockingReasons)
    ? (video.blockingReasons as { heading: string; message: string }[])
    : [];

  return (
    <PlatformShell>
      <Breadcrumbs
        items={[
          { label: 'Induction videos', href: '/platform/dashboard/induction-videos' },
          {
            label: video.jobSite.name,
            href: `/platform/dashboard/sites/${video.jobSiteId}/induction-video`,
          },
          { label: `Version ${video.version}` },
        ]}
      />
      <header className="mb-5 flex flex-wrap items-center gap-3">
        <div>
          <h1 className="text-2xl font-bold text-ink">
            Induction script · version {video.version}
          </h1>
          <p className="text-sm text-ink-muted">{video.jobSite.name}</p>
        </div>
        <span className="ml-auto">
          <InductionVideoStatusBadge status={video.status} stale={stale} />
        </span>
      </header>

      {blocking.length > 0 && (
        <section className="mb-5 rounded-xl border border-danger-500/40 bg-danger-50 p-4">
          <h2 className="text-sm font-bold text-danger-700">Information required</h2>
          <ul className="mt-2 space-y-2">
            {blocking.map((b) => (
              <li key={b.heading} className="text-sm text-danger-700">
                <span className="font-semibold">{b.heading}:</span> {b.message}
              </li>
            ))}
          </ul>
        </section>
      )}

      {stale && (
        <p className="mb-5 rounded-xl border border-hivis-500/40 bg-hivis-400/10 px-4 py-3 text-sm text-ink">
          This project’s information has changed since this version was
          generated. It is kept as it stands; generate a new version to take the
          changes in.
        </p>
      )}

      {warnings.length > 0 && (
        <div className="mb-5 rounded-xl border border-line bg-surface-sunken px-4 py-3">
          <p className="text-xs font-semibold text-ink">Worth knowing</p>
          <ul className="mt-1 space-y-1">
            {warnings.map((w) => (
              <li key={w} className="text-xs text-ink-muted">
                {w}
              </li>
            ))}
          </ul>
        </div>
      )}

      <ScriptEditor
        videoId={video.id}
        status={video.status}
        canApprove={canApprove}
        scenes={video.scenes.map((s) => ({
          id: s.id,
          sceneType: s.sceneType,
          heading: s.heading,
          narration: s.narration,
          required: s.required,
          sourceRefs: Array.isArray(s.sourceRefs) ? (s.sourceRefs as string[]) : [],
        }))}
      />

      <section className="mt-6 rounded-xl border border-line bg-surface p-4 shadow-card">
        <h2 className="text-sm font-bold text-ink">History</h2>
        <p className="mt-0.5 text-xs text-ink-subtle">
          {video.provider
            ? `Generated by ${video.provider}${video.model ? ` · ${video.model}` : ''}${
                video.promptVersion ? ` · ${video.promptVersion}` : ''
              }`
            : 'Not generated yet.'}
        </p>
        <ul className="mt-2 divide-y divide-line">
          {video.events.map((e) => (
            <li key={e.id} className="flex flex-wrap gap-2 py-2 text-sm">
              <span className="font-semibold text-ink">{e.action.replace(/_/g, ' ').toLowerCase()}</span>
              {e.detail && <span className="text-ink-muted">{e.detail}</span>}
              <span className="ml-auto text-xs text-ink-subtle">
                {formatDateTimeUK(e.createdAt)} · {e.actorName}
              </span>
            </li>
          ))}
        </ul>
      </section>
    </PlatformShell>
  );
}
