/**
 * PRODUCING A REUSABLE COMPANY VIDEO FROM A COMPANY MODULE.
 *
 * ── WHY THE SCRIPT IS NOT GENERATED BY THE MODEL ──────────────────────────
 *
 * scriptService already refuses to send module wording to the AI, and the reason it
 * gives is the reason this service follows the same rule:
 *
 *   "Their words were written and issued by a Director; a model that saw them might
 *    re-phrase company policy, and there is nothing for it to add."
 *
 * So a company video's script IS the module's approved narration, split into scenes
 * and used verbatim. That costs no tokens, cannot invent a company policy, and keeps
 * the module the single source of truth - which is the owner's instruction. The
 * review and edit step still exists, on the DRAFT, exactly as it does for a site
 * induction; what it cannot do is quietly become a second copy of approved wording,
 * because the published Library asset is not editable and a change means editing the
 * module and producing the video again.
 *
 * ── WHY THE RENDER NEEDS NO TRANSCODE ─────────────────────────────────────
 *
 * The finished video comes out of the same renderer at the same spec as every
 * library segment - 1080x1920, 25 fps, one stereo 44.1 kHz AAC track. So it is
 * already a valid segment: publishing files the rendered mp4 directly as the
 * revision's normalised footage, with no LibraryNormaliseJob at all. The captions
 * come free too, because narration already writes a WebVTT track.
 */
import {
  InductionVideoStatus,
  LibraryPlacement,
  LibraryProvenance,
  LibraryRevisionStatus,
} from '@prisma/client';
import { prisma } from '@/lib/prisma';
import type { VideoActor } from '@/services/inductionVideo/videoActor';
import type { ModuleActor } from '@/services/inductionModules/moduleActor';
/*
 * A STATIC import is safe here: libraryAssetService does not import this module, and
 * the only path back (libraryActions -> companyVideoService) is a dynamic import.
 */
import { createLibraryAsset } from '@/services/inductionVideo/libraryAssetService';
import { renderPath } from '@/services/inductionVideo/mediaStorage';

export type CompanyVideoResult<T> = { ok: true; value: T } | { ok: false; error: string };

/** Longest a single card should hold an operative's attention before it changes. */
const MAX_SENTENCES_PER_SCENE = 2;

/**
 * Split approved module wording into scenes WITHOUT changing a word.
 *
 * Paragraphs first, because whoever wrote the module already decided where the
 * breaks belong. A single long paragraph is grouped by sentence instead, so one
 * unbroken block does not become one card nobody can read.
 */
export function splitModuleNarration(narration: string): string[] {
  const paragraphs = narration
    .split(/\n\s*\n/)
    .map((p) => p.replace(/\s+/g, ' ').trim())
    .filter(Boolean);
  const source = paragraphs.length > 1 ? paragraphs : [narration.replace(/\s+/g, ' ').trim()];

  const scenes: string[] = [];
  for (const para of source) {
    const sentences = para.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g)?.map((x) => x.trim()) ?? [para];
    for (let i = 0; i < sentences.length; i += MAX_SENTENCES_PER_SCENE) {
      const chunk = sentences.slice(i, i + MAX_SENTENCES_PER_SCENE).join(' ').trim();
      if (chunk) scenes.push(chunk);
    }
  }
  return scenes.length ? scenes : [];
}

/**
 * Begin producing a video for a Library asset from its module's issued wording.
 *
 * Starts at SCRIPT_READY rather than DRAFT: there is no generation to wait for, so
 * the first thing the user sees is the script itself, ready to read.
 */
export async function startCompanyVideo(
  actor: VideoActor,
  assetId: string,
): Promise<CompanyVideoResult<{ videoId: string; version: number; scenes: number }>> {
  /*
   * WHO MAY PRODUCE ONE follows company MODULE authority exactly, because that is what
   * this is: preparing company content. Drafting a module is open to a Site Manager,
   * issuing it is a Director's decision - so producing a video is open to a Site
   * Manager and PUBLISHING it into the Library is not. Inventing a stricter rule here
   * would have quietly taken work away from the people already trusted with the
   * wording.
   */
  if (!actor.canManage) {
    return {
      ok: false,
      error: 'Only a Director, Site Manager or Admin Centre administrator may produce a company video.',
    };
  }
  const asset = await prisma.libraryAsset.findUnique({
    where: { id: assetId },
    select: {
      id: true, title: true, provenance: true, active: true, moduleId: true,
      module: {
        select: {
          id: true, title: true,
          revisions: {
            where: { status: 'ISSUED' },
            orderBy: { version: 'desc' },
            take: 1,
            select: { id: true, version: true, heading: true, narration: true },
          },
        },
      },
      productions: { select: { id: true, status: true, version: true } },
    },
  });
  if (!asset) return { ok: false, error: 'That library video no longer exists.' };
  if (!asset.active) return { ok: false, error: 'That library video is retired. Bring it back first.' };
  if (asset.provenance !== 'GENERATED') {
    return {
      ok: false,
      error:
        `“${asset.title}” holds uploaded footage. Producing a video for it here would ` +
        'replace footage somebody filmed; add a separate generated video instead.',
    };
  }
  if (!asset.module) {
    return {
      ok: false,
      error: 'Choose the company module this video is produced from before generating it.',
    };
  }
  const revision = asset.module.revisions[0];
  if (!revision) {
    return {
      ok: false,
      error:
        `“${asset.module.title}” has no issued wording yet. Issue the module, then produce ` +
        'the video from it.',
    };
  }

  /*
   * One production at a time: a second in flight would race the first to publish.
   * There is no SUPERSEDED status - superseding is recorded with supersededAt - so
   * "in flight" means anything not yet published.
   *
   * THE MESSAGE NAMES WHERE THE THING IS. It used to say only "Finish or delete it
   * first", which was advice with nowhere to take it: no screen rendered a company
   * production, so the version it named could not be reached, finished or deleted.
   * "Under way" on this asset's page is now that screen, and the wording points at
   * it - a refusal that names an obstacle owes the reader its location.
   */
  const inFlight = asset.productions.find((p) => p.status !== InductionVideoStatus.PUBLISHED);
  if (inFlight) {
    return {
      ok: false,
      error:
        `Version ${inFlight.version} of this video is already being produced. It is listed ` +
        'under “Under way” on this page, where you can open it to finish it or discard it.',
    };
  }

  const chunks = splitModuleNarration(revision.narration);
  if (chunks.length === 0) {
    return { ok: false, error: 'That module has no wording to turn into a video.' };
  }

  const latest = await prisma.inductionVideo.findFirst({
    where: { libraryAssetId: assetId },
    orderBy: { version: 'desc' },
    select: { version: true },
  });
  const version = (latest?.version ?? 0) + 1;

  const video = await prisma.inductionVideo.create({
    data: {
      scope: 'COMPANY',
      libraryAssetId: assetId,
      sourceModuleRevisionId: revision.id,
      version,
      // No script to generate: the wording is already approved.
      status: InductionVideoStatus.SCRIPT_READY,
      scenes: {
        create: chunks.map((narration, i) => ({
          sceneType: 'COMPANY_MODULE',
          order: i,
          heading: revision.heading,
          narration,
          required: true,
          // The module revision on the SCENE as well as the video: a re-issue of the
          // module must not change what an already-rendered video contains.
          moduleRevisionId: revision.id,
        })),
      },
      events: {
        create: {
          action: 'SCRIPT_GENERATED',
          actorName: actor.name,
          actorRealm: actor.realm,
          detail:
            `Produced from “${asset.module.title}” revision ${revision.version}, ` +
            `${chunks.length} scenes, wording unchanged.`,
        },
      },
    },
    select: { id: true, version: true },
  });

  return { ok: true, value: { videoId: video.id, version: video.version, scenes: chunks.length } };
}

/**
 * Publish a finished company video into the Library as a new revision.
 *
 * The rendered mp4 becomes the revision's NORMALISED footage directly - it already
 * matches the pipeline spec, so there is nothing to transcode - and the WebVTT the
 * narration step produced becomes its captions. The revision is left as a DRAFT so
 * the existing Library flow still governs what every project gets: somebody with
 * authority reads it, sees what will change, and issues it.
 */
export async function publishCompanyVideoToLibrary(
  actor: VideoActor,
  videoId: string,
): Promise<CompanyVideoResult<{ revisionId: string; version: number }>> {
  if (!actor.canApprove) {
    return { ok: false, error: 'Only a Director or an Admin Centre administrator may publish a company video.' };
  }
  const video = await prisma.inductionVideo.findUnique({
    where: { id: videoId },
    select: {
      id: true, status: true, videoBlobPath: true, captionsBlobPath: true,
      libraryAssetId: true, sourceModuleRevisionId: true, version: true,
      scenes: { select: { audioDurationMs: true } },
      libraryAsset: { select: { id: true, title: true } },
    },
  });
  if (!video || !video.libraryAssetId || !video.libraryAsset) {
    return { ok: false, error: 'That is not a company video.' };
  }
  if (!video.videoBlobPath) {
    return { ok: false, error: 'Render the video before publishing it to the Library.' };
  }
  if (!video.captionsBlobPath) {
    return {
      ok: false,
      error:
        'This video has no caption track yet. Narrate it again — captions are written ' +
        'with the narration, and a library video cannot be issued without them.',
    };
  }

  const durationMs = video.scenes.reduce((n, s) => n + (s.audioDurationMs ?? 0), 0);

  const existingDraft = await prisma.libraryAssetRevision.findFirst({
    where: { assetId: video.libraryAssetId, status: LibraryRevisionStatus.DRAFT },
    select: { id: true },
  });
  const nextVersion = existingDraft
    ? undefined
    : ((
        await prisma.libraryAssetRevision.findFirst({
          where: { assetId: video.libraryAssetId },
          orderBy: { version: 'desc' },
          select: { version: true },
        })
      )?.version ?? 0) + 1;

  const data = {
    // The render IS the segment: same renderer, same spec, nothing to transcode.
    normalisedBlobPath: video.videoBlobPath,
    normalisedBytes: null,
    durationMs: durationMs > 0 ? durationMs : null,
    captionsBlobPath: video.captionsBlobPath,
    captionsFileName: 'captions.vtt',
    normaliseError: null,
    sourceModuleRevisionId: video.sourceModuleRevisionId,
    preparedByName: actor.name,
    preparedByRealm: actor.realm,
  };

  const revision = existingDraft
    ? await prisma.libraryAssetRevision.update({
        where: { id: existingDraft.id },
        data,
        select: { id: true, version: true },
      })
    : await prisma.libraryAssetRevision.create({
        data: { assetId: video.libraryAssetId, version: nextVersion!, ...data },
        select: { id: true, version: true },
      });

  await prisma.libraryAssetEvent.create({
    data: {
      revisionId: revision.id,
      action: 'PRODUCED_IN_SITECOMPLY',
      actorName: actor.name,
      actorRealm: actor.realm,
      detail: `Produced in SiteComply from the company module (video version ${video.version}).`,
    },
  });
  await prisma.inductionVideo.update({
    where: { id: video.id },
    data: {
      status: InductionVideoStatus.PUBLISHED,
      publishedAt: new Date(),
      publishedByName: actor.name,
      publishedByRealm: actor.realm,
    },
  });
  /*
   * Earlier productions OF THIS ASSET become history, exactly as earlier versions of a
   * site induction do. Scoped by libraryAssetId and not by "no site", because the
   * latter is every company video of every asset.
   */
  await prisma.inductionVideo.updateMany({
    where: { libraryAssetId: video.libraryAssetId, id: { not: video.id }, supersededAt: null },
    data: { supersededAt: new Date() },
  });

  return { ok: true, value: { revisionId: revision.id, version: revision.version } };
}

/**
 * The Library asset a module's video lives in, creating it if there is not one yet.
 *
 * ── WHY THIS IS PROVISIONED AND NOT ASKED FOR ─────────────────────────────
 *
 * A generated company video has to live in a `LibraryAsset`, because that is the
 * object a site resolves footage from. But the user's intention is "make a video of
 * this module" — the asset is bookkeeping, and making them create one, mark it
 * GENERATED and point it back at the module they started from was the first and
 * worst step of the old flow. Nobody would guess it, and getting it wrong produced a
 * production that could not be finished.
 *
 * ── AND WHY PROVISIONING IT CHANGES NOTHING UNTIL THE VIDEO IS LIVE ───────
 *
 * Worth stating because it is the safety property that makes this acceptable. A site
 * leaves out a module's written scene only when footage REPLACES it, and
 * `replacedModuleIds` in `sceneRules` is built from `resolveLibraryForSite`, which
 * requires an ISSUED revision with a normalised segment and captions. An asset with
 * no issued revision resolves to nothing, so it appears in no manifest and suppresses
 * no wording. The swap happens at the moment the video is issued, which is exactly
 * when it should.
 *
 * Placement is COMPANY_BAND and the order is the module's own, so the footage takes
 * the module's place in the running order rather than moving it. The inclusion rules
 * are mirrored from the module for the same reason: the video is a richer delivery of
 * the same content, not a different decision about who sees it.
 */
export async function ensureGeneratedAssetForModule(
  actor: ModuleActor,
  moduleId: string,
): Promise<{ ok: true; assetId: string; created: boolean } | { ok: false; error: string }> {
  const module = await prisma.inductionModule.findUnique({
    where: { id: moduleId },
    select: {
      id: true,
      slug: true,
      title: true,
      order: true,
      mandatory: true,
      defaultIncluded: true,
      active: true,
      libraryAssets: {
        where: { provenance: 'GENERATED' },
        select: { id: true, active: true },
        orderBy: { createdAt: 'asc' },
      },
    },
  });
  if (!module) return { ok: false, error: 'That module does not exist.' };
  if (!module.active) {
    return {
      ok: false,
      error: 'This module is retired, so there is nothing to make a video for. Bring it back first.',
    };
  }

  const existing = module.libraryAssets.find((a) => a.active) ?? null;
  if (existing) return { ok: true, assetId: existing.id, created: false };

  /*
   * A RETIRED one is brought back rather than joined by a second. Two generated
   * assets for one module would both claim to replace it, and `replacedModuleIds`
   * would be satisfied by whichever resolved first.
   */
  const retired = module.libraryAssets[0] ?? null;
  if (retired) {
    await prisma.libraryAsset.update({ where: { id: retired.id }, data: { active: true } });
    return { ok: true, assetId: retired.id, created: false };
  }

  const created = await createLibraryAsset(actor, {
    // Prefixed so it cannot collide with a slug somebody typed for uploaded footage.
    slug: `MODULE_${module.slug}`,
    title: module.title,
    placement: LibraryPlacement.COMPANY_BAND,
    provenance: LibraryProvenance.GENERATED,
    order: module.order,
    moduleId: module.id,
    mandatory: module.mandatory,
    defaultIncluded: module.defaultIncluded,
  });
  if (!created.ok) return { ok: false, error: created.error };
  return { ok: true, assetId: created.value.assetId, created: true };
}
